# Generated by Django 5.0.14 on 2025-05-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_category_alter_article_main_page'),
    ]

    operations = [
    ]
